const {chromium}=require(process.env.ETL_PLAYWRIGHT||'playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.ETL_CHROMIUM?{executablePath:process.env.ETL_CHROMIUM}:{})});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],remote=[];
  page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  page.on('console',m=>{if(m.type()==='error' && /Content Security Policy|Refused/.test(m.text()))errors.push(m.text());});
  page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:'))remote.push(r.url());});
  await page.route('**/api/bootstrap',async route=>{const response=await route.fetch();const body=await response.json();body.source_connections=['ETL_SQL_TEST'];await route.fulfill({response,json:body});});
  await page.goto(process.env.ETL_TEST_URL||'http://127.0.0.1:8768');
  await page.waitForFunction(()=>document.querySelectorAll('#columns .select2').length>0);
  await page.waitForLoadState('networkidle');
  assert.doesNotMatch(await page.locator('#notice').innerText(),/Cannot set properties|Cannot read properties/,'Startup must not invoke inactive ordered-editor actions');
  assert.equal(await page.evaluate(()=>dirty),false,'Rendering controls must not mark a draft edited');
  await page.locator('#columns tr').first().locator('.source-select + .select2 .select2-selection').click();
  await page.locator('.select2-results__option').getByText('email',{exact:true}).click();
  assert.equal(await page.locator('#columns tr').first().locator('[data-field=value]').inputValue(),'email');
  const transforms=page.locator('#columns tr').first().locator('.transform-control');
  await transforms.locator('summary').click();
  while(await transforms.locator('[data-transform-action=remove]').count())await transforms.locator('[data-transform-action=remove]').first().click();
  await transforms.locator('select').selectOption('trim');await transforms.getByRole('button',{name:'Add transform',exact:true}).click();
  await transforms.locator('select').selectOption('empty_to_null');await transforms.getByRole('button',{name:'Add transform',exact:true}).click();
  await transforms.getByRole('button',{name:'Move transform 2 earlier',exact:true}).click();
  assert.equal(await page.locator('#columns tr').first().locator('[data-field=transforms]').inputValue(),'empty_to_null, trim');
  await page.locator('#preview').click();await page.locator('#results').waitFor();
  assert.match(await page.locator('#notice').innerText(),/Preview complete/);
  await page.locator('#new').click();await page.locator('#source-kind').selectOption('sqlserver');
  await page.locator('#connection + .select2 .select2-selection').click();
  await page.locator('.select2-results__option').getByText('ETL_SQL_TEST',{exact:true}).click();
  await page.route('**/api/discovery/namespaces',r=>r.fulfill({json:{items:[['dbo']],next_cursor:null}}));
  await page.route('**/api/discovery/datasets',r=>r.fulfill({json:{items:[{name:'BRANDS',kind:'table',key:'fixture'}],next_cursor:null}}));
  await page.route('**/api/columns',r=>r.fulfill({json:{columns:Array.from({length:300},(_,i)=>`FIELD_${i}`)}}));
  await page.locator('#schema + .source-select + .select2 .select2-selection').click();
  await page.locator('.select2-results__option').getByText('dbo',{exact:true}).click();
  await page.locator('#table + .source-select + .select2 .select2-selection').click();
  await page.locator('.select2-results__option').getByText('BRANDS',{exact:true}).click();
  await page.locator('#columns-add-all').waitFor();await page.locator('#columns-add-all').click();
  await page.waitForFunction(()=>document.querySelectorAll('#columns tr').length===300);
  const geometry=await page.evaluate(()=>({source:document.querySelector('#source-card').offsetHeight,mapping:document.querySelector('#mapping-card').offsetHeight,table:document.querySelector('#mapping-card .table-scroll').clientHeight,scroll:document.querySelector('#mapping-card .table-scroll').scrollHeight,bar:document.querySelector('.action-bar').getBoundingClientRect().bottom,viewport:innerHeight,resultsLast:!!(document.querySelector('#export-card').compareDocumentPosition(document.querySelector('#results-area'))&Node.DOCUMENT_POSITION_FOLLOWING)}));
  assert.ok(geometry.source<=460);assert.ok(geometry.mapping<=620);assert.ok(geometry.table<=360 && geometry.scroll>geometry.table);assert.equal(geometry.bar,geometry.viewport);assert.ok(geometry.resultsLast);
  const bottomGap=await page.evaluate(()=>document.documentElement.scrollHeight-(document.querySelector('footer').getBoundingClientRect().bottom+scrollY));
  assert.ok(bottomGap<220,`No hidden mapping controls extending past footer: ${bottomGap}px`);
  await page.locator('[data-section-link=mapping-card]').click();
  await page.screenshot({path:'data/qa/select2-desktop.png',fullPage:false});
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'No mobile page overflow');
  assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight-(document.querySelector('footer').getBoundingClientRect().bottom+scrollY))<220,'No blank overflow below footer on mobile');
  await page.screenshot({path:'data/qa/select2-mobile.png',fullPage:false});
  await page.locator('#new').click();
  const compact=await page.evaluate(()=>({mapping:document.querySelector('#mapping-card').offsetHeight,source:document.querySelector('#source-card').offsetHeight}));
  assert.ok(compact.mapping<500,'Empty mappings should shrink to their content, including wrapped selection actions');
  assert.ok(compact.source<=480,'Mobile source remains bounded');
  await page.setViewportSize({width:1440,height:1000});
  assert.ok(await page.locator('#mapping-card').evaluate(e=>e.offsetHeight)<480,'Desktop empty mappings should not reserve a full panel');
  assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);
  console.log('Mouse workflow passed: local Select2, source/table/column selection, transform ordering, preview, 300 columns, bounded sections, fixed actions, mobile, CSP.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
