const {chromium}=require(process.env.ETL_PLAYWRIGHT||"playwright");
const assert=require("node:assert/strict");
(async()=>{
 const browser=await chromium.launch({headless:true,...(process.env.ETL_CHROMIUM?{executablePath:process.env.ETL_CHROMIUM}:{})});
 try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.setDefaultTimeout(8000); page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message);});page.on('dialog',d=>d.accept());
  await page.goto(process.env.ETL_TEST_URL||'http://127.0.0.1:8769');
  await page.waitForFunction(()=>document.querySelector('#name').value.includes('Customers'));
  console.log('Loaded query fixture');
  await page.locator('#new').click();
  console.log('New draft');
  await page.locator('#source-kind').selectOption('sqlserver_query');
  console.log('Selected query');
  await page.getByRole('button',{name:'Refresh approved connections',exact:true}).click();
  await page.locator('#notice').filter({hasText:'Approved references loaded'}).waitFor();
  await page.locator('#query-connection').selectOption('ETL_SQL_QUERY_TEST');
  const sql='SELECT b.Code, b.Name, b.Amount FROM dbo.BRANDS b LEFT JOIN dbo.Regions r ON r.Code=b.Code WHERE b.Code <> ? ORDER BY b.Code;';
  await page.getByLabel('SELECT query',{exact:true}).fill(sql);
  await page.getByLabel('Ordered typed parameters (JSON)',{exact:true}).fill(JSON.stringify([{name:'excluded',type:'string',value:"'; DROP TABLE x; --"}]));
  await page.getByRole('button',{name:'Validate query',exact:true}).click();
  await page.locator('#notice').filter({hasText:'validated locally'}).waitFor();
  await page.getByRole('button',{name:'Inspect query columns',exact:true}).click();
  await page.locator('#notice').filter({hasText:'Query columns inspected'}).waitFor();
  assert.equal(await page.locator('#columns tr').count(),0);
  assert.match(await page.locator('#discovery-metadata').innerText(),/Amount/);
  await page.getByLabel('Source sample limit (1–100)',{exact:true}).fill('2');
  await page.getByRole('button',{name:'Read Source Sample',exact:true}).click();
  await page.locator('#discovery-sample').waitFor({state:'visible'});
  assert.match(await page.locator('#discovery-sample-status').innerText(),/2 records/);
  assert.match(await page.locator('#discovery-sample-table').innerText(),/003/);
  assert.equal(await page.locator('#results').isVisible(),false);
  await page.getByLabel('Ordered typed parameters (JSON)',{exact:true}).fill(JSON.stringify([{name:'excluded',type:'string',value:'no match'}]));
  assert.equal(await page.locator('#discovery-sample').isVisible(),false);
  await page.getByRole('button',{name:'Inspect query columns',exact:true}).click();
  await page.locator('#notice').filter({hasText:'Query columns inspected'}).waitFor();
  await page.getByRole('button',{name:'Use this dataset',exact:true}).click();
  assert.equal(await page.getByLabel('SELECT query',{exact:true}).inputValue(),sql);
  assert.equal(await page.locator('#columns tr').count(),0);
  // The legacy inspect shortcut must not silently generate query mappings.
  await page.getByRole('button',{name:'Read source columns',exact:true}).click();
  await page.locator('#notice').filter({hasText:'source columns available'}).waitFor();
  assert.equal(await page.locator('#columns tr').count(),0);
  await page.locator('#add').click();
  await page.getByLabel('Field 1 name',{exact:true}).fill('CustomerCode');
  await page.getByLabel('Field 1 value',{exact:true}).fill('Code');
  await page.getByRole('button',{name:'Processed Preview (100 rows)',exact:true}).click();
  await page.locator('#notice').filter({hasText:'Preview complete'}).waitFor();
  assert.match(await page.locator('#counts').innerText(),/25/);
  await page.getByRole('button',{name:'Save pipeline',exact:true}).click();
  await page.locator('#notice').filter({hasText:'Pipeline saved'}).waitFor();
  await page.locator('#run').click();
  await page.waitForFunction(()=>document.querySelector('#runs').textContent.includes('completed'));
  await page.locator('#query-sql').fill('SELECT 1 INTO dbo.bad');
  await page.getByRole('button',{name:'Validate query',exact:true}).click();
  await page.locator('#notice.error').waitFor();
  assert.match(await page.locator('#notice').innerText(),/unsupported/);
  await page.locator('#pipelines [data-pipeline]').first().click();
  assert.equal(await page.getByLabel('SELECT query',{exact:true}).inputValue(),sql);
  assert.deepEqual(errors,[]);
  console.log('Query browser acceptance passed: inspect, raw sample, explicit mapping, preview, snapshot reload, rejection.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
